const CHANGE_COUNTRY = "CHANGE_COUNTRY";
const CHANGE_COUNTRIES_DATA = "CHANGE_COUNTRIES_DATA";
const CHANGE_COUNTRY_SELECTED_CODE = "CHANGE_COUNTRY_SELECTED_CODE";
const CHANGE_COUNTRY_INFO = "CHANGE_COUNTRY_INFO";

export { CHANGE_COUNTRY, CHANGE_COUNTRIES_DATA, CHANGE_COUNTRY_SELECTED_CODE, CHANGE_COUNTRY_INFO };